
export const FETCH_CLIENTS_REQUEST = 'FETCH_CLIENTS_REQUEST';
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';
export const FETCH_CLIENTS_ERROR = 'FETCH_CLIENTS_ERROR';

export const SHOW_CLIENT_INFO = 'SHOW_CLIENT_INFO';
export const SEARCH_CLIENTS = 'SEARCH_CLIENT';